### ISSUE TITLE
Blood arsenal config change request

### ISSUE THREAD

**Issue by lawl281** [AwesomesauceServer/Refresh-v1-Configs#2]
90 miscellaneous {
91    # Provides a temporary recipe for the Crystal Cluster blocks in vanilla Blood Magic for those who want 
         access to Tier 6 [default: false]
92    B:crystalClusterEnabled=false

90 miscellaneous {
91    # Provides a temporary recipe for the Crystal Cluster blocks in vanilla Blood Magic for those who want 
         access to Tier 6 [default: false]
92    B:crystalClusterEnabled=true

**Comment by AwesomesauceServer** [comment]
Added. https://github.com/AwesomesauceServer/Refresh-v1-Configs/commit/a209c5cb7d9d3e170694707866e307b694c9f69f

Will be active next server restart.
